### PR TITLE
Rollback to 1.0.1 and launch settings

### PR DESCRIPTION
**Pull request by DaniilSokolyuk**

### CODE REVIEW

**Comment by ENikS** [comment]
Why would we want to roll back to 1.0.1 ?! 
I don't think so.

**Comment by DaniilSokolyuk** [comment]
In microsoft di 2.0.0 you make some breaking changes and asp net core not working anymore

**Comment by ENikS** [comment]
We need to fix core code, not go back to 1.0.1

**Comment by ENikS** [comment]
Fixed

**Pull request closed without merging**
